# docker-compose.yml
version: '3.8'
services:
  backend:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env

  webapp:
    build:
      context: .
      dockerfile: Dockerfile.webapp
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - BACKEND_URL=http://backend:8000
    depends_on:
      - backend